image: node:22

deploy-pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
  pages: true
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
